// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrygzkzynpysranadvhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyeWd6a3p5bnB5c3JhbmFkdmhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2Mjc1MjYsImV4cCI6MjA1NjIwMzUyNn0.5yo6LeFiJvFjSo9NRelaqjqWKWws_0rjZIRX_s6nnTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);