// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibqzbmsawlzdtaxqwzaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlicXpibXNhd2x6ZHRheHF3emFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MTQxMDgsImV4cCI6MjA1ODA5MDEwOH0.lv2zlWbCUHUDISDp57jtU1-XvBpZmip9Jm8rVBKA7zU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);